---
language: node_js
node_js:
- '0.11'
- '0.10'
after_success:
- make coveralls
- '[[ -n "$TRAVIS_TAG" ]] && make gh-pages'
deploy:
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: fU0jT6FFZJyJKZ4h7bQM1A4NTV7cAEkqBQv0XDVsXKjHTY8vtQBfHiUTAYY/i1rQor3pFZBUHeDQ9hoRwhnVXR5Ds03wNBxu3ezQsTM9cTRPn4ZvgPjaPKEhkhM/GqL2Mz7S00XK8AzQZeBjHTOjRMEtAfRPZmPn0AyNWCMulnU=
  on:
    tags: true
    node: '0.10'
    repo: Dreamscapes/ledctl
    all_branches: true
matrix:
  allow_failures:
  - node_js: '0.11'
env:
  global:
    secure: medK5FkcYvntB64osQZP3orfU5SvcY7cxxF1DeFO1B23MeB2Vjs9wCWHm0UuyF536tQgOB4uhmrN1HIXt0fNEPElu2lGiQxrTW7yxxLQaeuaA+nLR1rBpRPn9UNeMbfqtwbyzRhfTCHPPptdy78Qz2QUTSQIZeIgaii/V85jV/A=
